version: '3'
services:
  notebook:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --notebook-dir=/workspace/notebooks --NotebookApp.token='' --NotebookApp.password='' 